before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
    goarm:
      - "6"
      - "7"
    # List of combinations of GOOS + GOARCH + GOARM to ignore.
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
archives:
  - name_template: "{{ .Os }}-{{ .Arch }}"
    format: binary
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  use: github-native
release:
  draft: true